#!/bin/bash
rtName="$1"
idName="$2"
id="$rtName.$idName"
if [[ -z "$idName" ]]
    then
        echo -e "\nYou need to provide two arguments for this script to work. \nUsage: make-go-dir <root directory name> <identifier name>\n" 
    else
        echo -e "\nI am about to create a directory structure named *$rtName*"
        echo "Do you want to continue? [Yes\No]"
        read ans
        ans="${ans,,}"     
fi

if [[ "$ans" == "yes" ]]
    then
        echo "Create directory structure.."
    else
        echo "Abort."
        exit 0
fi
mkdir "$rtName"
cd "$rtName"
mkdir "internals"
mkdir "migrations"
mkdir "remote"
go mod init "$id"
touch "Makefile"
mkdir "bin"
mkdir "cmd"
    cd "cmd"
        mkdir "api"
            cd "api"
                touch "main.go"
echo "
//File: cmd/api/main.go                
package main
                
import \"fmt\"
                
func main() {
fmt.Println(\"Hello world!\")
} " > main.go

echo -e "
I have created a *main.go* file for you to test the directory structure.\nType *go run ./cmd/api* at the root directory of your project to test your project.\nThank you."